### ISSUE TITLE
ERROR: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.

### ISSUE THREAD

**Issue by Memphisartguy** [pfitzer/youtube2mp3#139]
Can't find it even after installed. 

C:\Windows\system32>youtube2mp3 -d  "S:\Media" -y "https://www.youtube.com/watch?v=z5NCvdAXZ9w"
[youtube] z5NCvdAXZ9w: Downloading webpage
[youtube] z5NCvdAXZ9w: Downloading player 72d3c60a
[download] Destination: The Cog is Dead - POTATO SONG (Cuz I Want To) [KESHA Cover]-z5NCvdAXZ9w.m4a
[download] 100% of 3.62MiB in 01:09
Done downloading, now converting ...
The Cog is Dead - POTATO SONG (Cuz I Want To) [KESHA Cover]-z5NCvdAXZ9w.m4a
WARNING: z5NCvdAXZ9w: writing DASH m4a. Only some players support this container. Install ffmpeg or avconv to fix this automatically.
ERROR: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 2115, in post_process
    files_to_delete, info = pp.run(info)
                            ^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 275, in run
    filecodec = self.get_audio_codec(path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 166, in get_audio_codec
    raise PostProcessingError('ffprobe/avprobe and ffmpeg/avconv not found. Please install one.')
youtube_dl.utils.PostProcessingError: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\youtube2mp3\cli.py", line 48, in run
    ydl.download([options.youtube_url])
  File "C:\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 2068, in download
    res = self.extract_info(
          ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 847, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 881, in process_ie_result
    return self.process_video_result(ie_result, download=download)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 1692, in process_video_result
    self.process_info(new_info)
  File "C:\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 2050, in process_info
    self.post_process(filename, info_dict)
  File "C:\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 2117, in post_process
    self.report_error(e.msg)
  File "C:\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "C:\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\youtube2mp3.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\youtube2mp3\cli.py", line 93, in main
    y2mp3.run()
  File "C:\Python311\Lib\site-packages\youtube2mp3\cli.py", line 51, in run
    print(e.message)
          ^^^^^^^^^
AttributeError: 'DownloadError' object has no attribute 'message'

**Comment by pfitzer** [comment]
How did you installed ffmpeg?

Ubuntu and debian:
sudo apt-get install ffmpeg

macOS:
brew install ffmpeg

Windows:
choco install ffmpeg


on win10 with ffmpeg over choco
```
PS C:\windows\system32> youtube2mp3 -y https://www.youtube.com/watch?v=8f0Qy7yzDDc -d C:\Users\pfitz\Music\
[youtube] 8f0Qy7yzDDc: Downloading webpage
[download] Destination: Vynek - Attention [Dark Monkey Music]-8f0Qy7yzDDc.webm
[download] 100% of 2.90MiB in 00:47
Done downloading, now converting ...
Vynek - Attention [Dark Monkey Music]-8f0Qy7yzDDc.webm
[ffmpeg] Destination: Vynek - Attention [Dark Monkey Music]-8f0Qy7yzDDc.mp3
Deleting original file Vynek - Attention [Dark Monkey Music]-8f0Qy7yzDDc.webm (pass -k to keep)
[tagging]: Vynek - Attention [Dark Monkey Music]-8f0Qy7yzDDc.mp3
```
